gitlab-backup: time module is required for Time.parse
Solve the problem:

    NoMethodError: undefined method `parse' for Time:Class

--------

kirr: it probaly started to fail due to gitlab codebase upgrade, as eariler gitlab-rake was likely requiring "time" and now does not.

/reviewed-by @kirr
/reviewed-on https://lab.nexedi.com/kirr/git-backup/merge_requests/6